### PR TITLE
Add colorized query logging in debug environment from calls to server

### PR DESCRIPTION
**Pull request by zhbanton**
- Didn't write any tests because we were unsure of how to do so without mocks or stubs, which do not currently appear in the test suite

### CODE REVIEW

**Comment by lukeasrodgers** [comment]
ping @veny -- anything we could do to improve/alter this PR to get it landed? Thanks.

**Comment by veny** [comment]
2 questions before merge:
* did you try it on Windows? how does it behave? I do believe it will damage the output. see here for more info:
 * http://stackoverflow.com/questions/77744/how-can-i-change-the-text-color-in-the-windows-command-prompt
* why the method `query_log` is used only for a few outputs in Client? why not in entire solution?

**Comment by zhbanton** [comment]
Thanks for the feedback.  Based on this screenshot from our vm (using putty to ssh into our virtualbox), the solution appears to work on windows, although we have not thoroughly tested.  In terms of your second point, we originally decided to implement this solution to see how long our odb queries were taking and avoid possible n+1 queries, so highlighting the result of db queries were our primary concern.  We were inspired by Rails here, which in general, only colorizes query output.

screen shot 2015-06-25 at 12 00 05 pm 2

**Comment by zhbanton** [comment]
View along side rails output:

screen shot 2015-06-25 at 12 11 35 pm

**Pull request merged**
